# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    Hippy\Config\Partial\AbstractPartial:
      tags: [Hippy.config.partial]
    Hippy\Api\Service\Base\Check\CheckInterface:
      tags: [Hippy.check.handler]
    Hippy\Api\Transformer\OpenApi\TransformerInterface:
      tags: [Hippy.openapi.transformer]
    Hippy\Api\Transformer\Logging\Strategy\StrategyInterface:
      tags: [Hippy.logging.strategy]

  Hippy\Api\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Entity/'
      - '../../Kernel.php'
      - '../tests/'

  Hippy\Api\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  Hippy\Api\Listener\ExceptionStrategy\UnhandledExceptionStrategy:
    tags: [{ name: Hippy.exception.strategy, priority: 0 }]
  Hippy\Api\Listener\ExceptionStrategy\UnhandledHttpExceptionStrategy:
    tags: [{ name: Hippy.exception.strategy, priority: 1 }]
  Hippy\Api\Listener\ExceptionStrategy\MethodNotAllowedExceptionStrategy:
    tags: [{ name: Hippy.exception.strategy, priority: 2 }]
  Hippy\Api\Listener\ExceptionStrategy\ServiceExceptionStrategy:
    tags: [{ name: Hippy.exception.strategy, priority: 5 }]
  Hippy\Api\Listener\ExceptionEventSubscriber:
    arguments:
      $strategies: !tagged_iterator Hippy.exception.strategy

  Hippy\Api\Service\Base\OpenapiService:
    arguments:
      $transformers: !tagged_iterator Hippy.openapi.transformer

  Hippy\Api\Service\Base\CheckService:
    arguments:
      $checks: !tagged_iterator Hippy.check.handler

  Hippy\Api\Transformer\Logging\Transformer:
    arguments:
      $strategies: !tagged_iterator Hippy.logging.strategy
